name: build-armtemplate

on:
  workflow_call:

jobs:
  lint-bicep:
    name: Lint Bicep
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Bicep
      run: | 
        curl -Lo bicepinstall https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
        chmod +x ./bicepinstall
        sudo mv ./bicepinstall /usr/local/bin/bicep
        bicep --help
     
    - name: Build Bicep
      run: |
        bicep build ./infrastructure/bicep/main.bicep

    - name: Upload ARM Template as workflow artifact
      uses: actions/upload-artifact@v3
      with:
        name: armtemplate
        path: ./infrastructure/bicep/main.json